# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty

# Setup
title:            Colin Marsch 
tagline:          'Android Developer'
description:      ''
url:              https://colinmarsch.me
baseurl:          /

author:
  name:           'Colin Marsch'
  url:            https://twitter.com/colinmarsch

paginate:         5

plugins:          [jekyll-paginate]
