# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty

# Setup
title:            Colin Marsch 
tagline:          'Android Engineer'
description:      ''
url:              https://colinmarsch.ca/
baseurl:          https://colinmarsch.ca/

author:
  name:           'Colin Marsch'
  url:            https://twitter.com/colinmarsch

paginate:         5

plugins:          [jekyll-paginate]
